algoritmo "area terreno"
// Disciplina:  LOPAL (Lógica de Programação)

// F9 (Executa meu código)

// Autor: Enzo Ferrari
// Data: 13/04/2026
var

 largura, comprimento, area: real

inicio
// entrada de dados

 escreva("Digite a largura: ")
 leia(largura)
 
 escreva("Digite o comprimento: ")
 leia(comprimento)

 area <- largura * comprimento

 limpatela

 escreva("Area do terreno: ", area)
 
fimalgoritmo
