algoritmo "soma dois numeros"
// Disciplina:  LOPAL (Lógica de Programação)

// F9 (Executa meu código)

// Autor: Enzo Ferrari
// Data: 13/04/2026
var

 A, B, SOMA: real

inicio
// entrada de dados

 escreva("Digite o primeiro numero: ")
 leia(A)
 escreva("Digite o segundo numero: ")
 leia(B)

//Conta

 SOMA <- A + B
 
 limpatela

 escreva("Resultado: ", SOMA)

fimalgoritmo
