algoritmo "area trapezio"
// Disciplina:  LOPAL (Lógica de Programação)

// F9 (Executa meu código)

// Autor: Enzo Ferrari
// Data: 13/04/2026
var

 baseMaior, baseMenor, altura, area: real

inicio
// entrada de dados

 escreva("Digite a base maior: ")
 leia(baseMaior)
 escreva("Digite a base menor: ")
 leia(baseMenor)
 escreva("Digite a altura: ")
 leia(altura)

 area <- (baseMaior + baseMenor) * altura / 2

 limpatela

 escreva("Area do trapezio: ", area)

fimalgoritmo
